'use client';

import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Boxes,IndianRupee,MapPinned,PackageCheck,RefreshCw,ShieldCheck,Store,Truck,Users} from 'lucide-react';
import {AdminOverview,api,DeliveryTask,gaonApi,Merchant,MerchantStatus,User} from '@/lib/api';
import {Nav} from '@/components/Nav';

const money=(value:string|number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value||0));
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());
type AdminUser=User&{is_super_admin?:boolean};
type ActiveDelivery={id:string;order_id:string;order_number?:string;delivery_partner_id?:string;rider_name?:string;rider_phone?:string;status:string;assigned_at?:string;store_name?:string;store_landmark?:string;customer_landmark?:string};

export default function Admin(){
  const[merchants,setMerchants]=useState<Merchant[]>([]);const[users,setUsers]=useState<AdminUser[]>([]);const[tasks,setTasks]=useState<DeliveryTask[]>([]);const[active,setActive]=useState<ActiveDelivery[]>([]);const[riderFor,setRiderFor]=useState<Record<string,string>>({});const[me,setMe]=useState<AdminUser|null>(null);const[overview,setOverview]=useState<AdminOverview|null>(null);const[msg,setMsg]=useState('');const[busy,setBusy]=useState('');
  async function load(){try{const[current,m,o,u,t,a]=await Promise.all([gaonApi.me(),gaonApi.merchants(),gaonApi.adminOverview(),gaonApi.adminUsers(),gaonApi.availableDeliveryTasks(),api<ActiveDelivery[]>('/admin/deliveries/active')]);setMe(current as AdminUser);setMerchants(m);setOverview(o);setUsers(u as AdminUser[]);setTasks(t);setActive(a)}catch(error:any){setMsg(error.message)}}
  useEffect(()=>{load()},[]);
  async function changeStatus(id:string,status:MerchantStatus){setBusy(id);try{await gaonApi.updateMerchantStatus(id,status);await load();setMsg(status==='approved'?'Merchant activated.':'Merchant suspended and storefronts hidden.')}catch(error:any){setMsg(error.message)}finally{setBusy('')}}
  async function role(user:AdminUser,nextRole:User['role']){setBusy(user.id);try{await gaonApi.updateUserRole(user.id,nextRole,true);await load();setMsg(nextRole==='delivery'?'Delivery partner activated.':nextRole==='admin'?'Administrator access granted.':'User role updated.')}catch(error:any){setMsg(error.message)}finally{setBusy('')}}
  async function assign(task:DeliveryTask){const riderId=riderFor[task.id];if(!riderId){setMsg('Select a rider before assigning this delivery.');return}setBusy(task.id);try{await gaonApi.assignDelivery(task.id,riderId);const rider=users.find(user=>user.id===riderId);setRiderFor(current=>{const next={...current};delete next[task.id];return next});await load();setMsg(`${task.order_number} assigned to ${rider?.full_name||rider?.phone||'delivery partner'}.`)}catch(error:any){setMsg(error.message)}finally{setBusy('')}}
  async function unassign(delivery:ActiveDelivery){if(delivery.status!=='assigned')return;setBusy(delivery.id);try{await api(`/admin/deliveries/${delivery.id}/unassign`,{method:'POST'});await load();setMsg(`${delivery.order_number||'Delivery'} returned to the assignment queue.`)}catch(error:any){setMsg(error.message)}finally{setBusy('')}}
  async function push(){setBusy('push');try{const result=await gaonApi.flushNotifications();setMsg(`Notification dispatch: ${result.events} events, ${result.pushes} pushes.`)}catch(error:any){setMsg(error.message)}finally{setBusy('')}}
  const pipeline=useMemo(()=>overview?Object.entries(overview.orders.by_status):[],[overview]);const riders=useMemo(()=>users.filter(user=>user.role==='delivery'&&user.is_active&&user.is_verified),[users]);const busyRiderIds=useMemo(()=>new Set(active.map(delivery=>delivery.delivery_partner_id).filter(Boolean) as string[]),[active]);const isSuperAdmin=Boolean(me?.is_super_admin);
  return <><Nav/><main className="container section">
    <div className="sectionHead"><div><span className="eyebrow">Pilot command centre</span><h2>{isSuperAdmin?'Super Admin dashboard':'Admin dashboard'}</h2><p className="muted">Marketplace health, merchant approvals, rider dispatch and notification operations.</p></div><div className="row">{isSuperAdmin&&<span className="badge"><ShieldCheck size={15}/> Protected Super Admin</span>}<button className="btn secondary" disabled={busy==='push'} onClick={push}>Dispatch notifications</button><button className="btn secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div></div>
    {msg&&<div className="notice">{msg}</div>}
    <div className="statsGrid"><div className="card statCard"><Users/><span className="statValue">{overview?.users??'—'}</span><strong>Users</strong><span className="muted">Marketplace accounts</span></div><div className="card statCard"><MapPinned/><span className="statValue">{overview?.villages??'—'}</span><strong>Villages</strong><span className="muted">Active coverage</span></div><div className="card statCard"><Store/><span className="statValue">{overview?.active_stores??'—'}</span><strong>Live stores</strong><span className="muted">Customer storefronts</span></div><div className="card statCard"><Truck/><span className="statValue">{overview?.operations.active_delivery_partners??0}</span><strong>Riders</strong><span className="muted">Active delivery partners</span></div><div className="card statCard"><IndianRupee/><span className="statValue">{overview?money(overview.gross_order_value):'—'}</span><strong>Order value</strong><span className="muted">Non-cancelled GMV</span></div><div className="card statCard"><PackageCheck/><span className="statValue">{overview?.orders.total??'—'}</span><strong>Orders</strong><span className="muted">All-time volume</span></div><div className="card statCard"><AlertTriangle/><span className="statValue">{overview?.operations.low_stock_listings??'—'}</span><strong>Low stock</strong><span className="muted">Listings at 5 or less</span></div><div className="card statCard"><Boxes/><span className="statValue">{overview?.operations.ready_unassigned_deliveries??'—'}</span><strong>Awaiting rider</strong><span className="muted">Ready and unassigned</span></div></div>
    <section className="section splitGrid"><div className="panel"><h2 className="subhead">Order pipeline</h2><div className="stack">{pipeline.map(([status,count])=><div className="metricRow" key={status}><span>{label(status)}</span><strong>{count}</strong></div>)}</div></div><div className="panel"><h2 className="subhead">Merchant health</h2><div className="stack"><div className="metricRow"><span>Pending review</span><strong>{overview?.merchants.pending??0}</strong></div><div className="metricRow"><span>Approved</span><strong>{overview?.merchants.approved??0}</strong></div><div className="metricRow"><span>Suspended</span><strong>{overview?.merchants.suspended??0}</strong></div></div></div></section>
    <section className="section"><div className="panel"><div className="row space"><div><h2 className="subhead">Delivery dispatch</h2><p className="muted">Assign ready orders to active verified riders. Busy riders stay unavailable until their current delivery is released or completed.</p></div><span className="badge">{tasks.length} awaiting assignment</span></div><div className="tableWrap"><table className="table"><thead><tr><th>Order</th><th>Pickup</th><th>Drop</th><th>Total</th><th>Rider</th><th>Action</th></tr></thead><tbody>{tasks.map(task=><tr key={task.id}><td><strong>{task.order_number}</strong><div className="muted small">{label(task.payment_method)} • {label(task.payment_status)}</div></td><td><strong>{task.store_name}</strong><div className="muted small">{task.store_landmark||'Exact store pin available'}</div></td><td><strong>{task.recipient_name||'Customer'}</strong><div className="muted small">{task.customer_landmark}</div></td><td>{money(task.total)}</td><td><select aria-label={`Rider for ${task.order_number}`} value={riderFor[task.id]||''} onChange={event=>setRiderFor(current=>({...current,[task.id]:event.target.value}))}><option value="">Select rider</option>{riders.map(rider=><option key={rider.id} value={rider.id} disabled={busyRiderIds.has(rider.id)}>{rider.full_name||rider.phone}{busyRiderIds.has(rider.id)?' • busy':''}</option>)}</select></td><td><button className="btn" disabled={busy===task.id||!riderFor[task.id]} onClick={()=>assign(task)}>Assign</button></td></tr>)}{!tasks.length&&<tr><td colSpan={6} className="muted">No ready deliveries are waiting for assignment.</td></tr>}</tbody></table></div></div></section>
    <section className="section"><div className="panel"><div className="row space"><div><h2 className="subhead">Active deliveries</h2><p className="muted">Recover a mistaken assignment before pickup. Picked-up orders stay locked to their rider.</p></div><span className="badge">{active.length} active</span></div><div className="tableWrap"><table className="table"><thead><tr><th>Order</th><th>Rider</th><th>Route</th><th>Status</th><th>Recovery</th></tr></thead><tbody>{active.map(d=><tr key={d.id}><td><strong>{d.order_number||d.order_id}</strong></td><td>{d.rider_name||d.rider_phone||'Assigned rider'}</td><td><div>{d.store_name||'Store'}</div><div className="muted small">{d.store_landmark||'Pickup'} → {d.customer_landmark||'Customer'}</div></td><td><span className={`badge status-${d.status}`}>{label(d.status)}</span></td><td>{d.status==='assigned'?<button className="btn dangerBtn" disabled={busy===d.id} onClick={()=>unassign(d)}>Unassign</button>:<span className="muted small">Already picked up</span>}</td></tr>)}{!active.length&&<tr><td colSpan={5} className="muted">No active deliveries.</td></tr>}</tbody></table></div></div></section>
    <section className="section"><div className="panel"><h2 className="subhead">Merchant control</h2><div className="tableWrap"><table className="table"><thead><tr><th>Business</th><th>Status</th><th>GSTIN</th><th>Action</th></tr></thead><tbody>{merchants.map(merchant=><tr key={merchant.id}><td><strong>{merchant.business_name}</strong></td><td><span className={`badge status-${merchant.status}`}>{label(merchant.status)}</span></td><td>{merchant.gstin||'—'}</td><td>{merchant.status!=='approved'?<button disabled={busy===merchant.id} className="btn" onClick={()=>changeStatus(merchant.id,'approved')}>{merchant.status==='pending'?'Approve':'Reactivate'}</button>:<button disabled={busy===merchant.id} className="btn dangerBtn" onClick={()=>changeStatus(merchant.id,'suspended')}>Suspend</button>}</td></tr>)}{!merchants.length&&<tr><td colSpan={4}>No merchant applications yet.</td></tr>}</tbody></table></div></div></section>
    <section className="section"><div className="panel"><h2 className="subhead">People, riders & administrators</h2><p className="muted">Admins can manage pilot operations and rider access. Only the protected Super Admin can grant or remove administrator access.</p><div className="tableWrap"><table className="table"><thead><tr><th>Person</th><th>Phone</th><th>Role</th><th>Action</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td>{user.full_name||'Unnamed user'}</td><td>{user.phone}</td><td><span className="badge">{user.is_super_admin?'Super Admin':label(user.role)}</span></td><td><div className="row">{user.is_super_admin?<span className="muted">Protected</span>:<>{user.role==='customer'&&<button className="btn" disabled={busy===user.id} onClick={()=>role(user,'delivery')}>Activate rider</button>}{user.role==='delivery'&&<button className="btn secondary" disabled={busy===user.id} onClick={()=>role(user,'customer')}>Remove rider role</button>}{isSuperAdmin&&user.role!=='admin'&&<button className="btn secondary" disabled={busy===user.id} onClick={()=>role(user,'admin')}>Make admin</button>}{isSuperAdmin&&user.role==='admin'&&<button className="btn dangerBtn" disabled={busy===user.id} onClick={()=>role(user,'customer')}>Remove admin</button>}</>}</div></td></tr>)}</tbody></table></div></div></section>
  </main></>;
}
