'use client';
import {useEffect,useMemo,useState} from 'react';
import {BadgeIndianRupee,RefreshCw} from 'lucide-react';
import {getToken} from '@/lib/api';
import {Nav} from '@/components/Nav';

type Settlement={id:string;order_id:string;store_id:string;payment_method:string;gross_amount:string;merchant_amount:string;delivery_fee_amount:string;status:string;created_at:string;settled_at?:string|null};
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
const money=(v:string)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v));
export default function Settlements(){const[rows,setRows]=useState<Settlement[]>([]);const[error,setError]=useState('');const[loading,setLoading]=useState(true);async function load(){setLoading(true);try{const token=getToken();if(!token)throw new Error('Login required');const r=await fetch(`${API}/payments/settlements`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw new Error(`Settlement ledger unavailable (${r.status})`);setRows(await r.json());setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);const totals=useMemo(()=>rows.reduce((a,r)=>({gross:a.gross+Number(r.gross_amount),merchant:a.merchant+Number(r.merchant_amount),fees:a.fees+Number(r.delivery_fee_amount)}),{gross:0,merchant:0,fees:0}),[rows]);return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Merchant finance</span><h2>Settlement ledger</h2><p className="muted">Backend-authoritative order proceeds. This view never changes settlement status.</p></div><button className="btn secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>{error&&<div className="notice">{error}</div>}<div className="statsGrid"><div className="card statCard"><BadgeIndianRupee/><span className="statValue">{money(String(totals.gross))}</span><strong>Gross paid value</strong></div><div className="card statCard"><span className="statValue">{money(String(totals.merchant))}</span><strong>Merchant proceeds</strong></div><div className="card statCard"><span className="statValue">{money(String(totals.fees))}</span><strong>Delivery fees</strong></div></div><div className="panel tableWrap"><table className="table"><thead><tr><th>Order</th><th>Method</th><th>Gross</th><th>Merchant</th><th>Delivery fee</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.order_id.slice(0,8)}</strong><div className="muted small">{new Date(r.created_at).toLocaleString('en-IN')}</div></td><td>{r.payment_method.toUpperCase()}</td><td>{money(r.gross_amount)}</td><td>{money(r.merchant_amount)}</td><td>{money(r.delivery_fee_amount)}</td><td><span className={`badge status-${r.status}`}>{r.status.replaceAll('_',' ')}</span></td></tr>)}{!loading&&rows.length===0&&<tr><td colSpan={6} className="muted">No settlement entries yet.</td></tr>}</tbody></table>{loading&&<p className="muted">Loading settlement ledger…</p>}</div></main></>}
