'use client';
import Link from 'next/link';
import {useState} from 'react';
import {LocateFixed,ShoppingBag,Sparkles} from 'lucide-react';
import {api} from '@/lib/api';
import {Nav} from '@/components/Nav';

type FeedItem={listing_id:string;store_id:string;store_name:string;name:string;brand?:string;unit:string;category:string;price:string;distance_km:number;reason:string};
export default function ForYouPage(){
 const[items,setItems]=useState<FeedItem[]>([]);const[personalized,setPersonalized]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 function locate(){if(!navigator.geolocation){setError('Location is unavailable in this browser. Explore the marketplace instead.');return}setLoading(true);setError('');navigator.geolocation.getCurrentPosition(async p=>{try{const q=new URLSearchParams({latitude:String(p.coords.latitude),longitude:String(p.coords.longitude),radius_km:'20',limit:'20'});const data=await api<{personalized:boolean;items:FeedItem[]}>(`/discovery/for-you?${q}`);setItems(data.items);setPersonalized(data.personalized)}catch(e:any){setError(e.message)}finally{setLoading(false)}},()=>{setError('Location permission was not granted. You can still browse by area, landmark, city, village or pincode.');setLoading(false)},{enableHighAccuracy:false,timeout:10000})}
 return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">For you</span><h2>Useful things available nearby</h2><p className="muted">{personalized?'Ranked using your delivered-order history plus nearby live availability.':'Use your current location to build a nearby feed. New customers see live local availability without pretending it is personalized.'}</p></div><button className="btn" onClick={locate} disabled={loading}><LocateFixed size={17}/>{loading?'Checking…':'Use current location'}</button></div>{error&&<div className="notice">{error}</div>}{!items.length&&!loading&&!error&&<div className="panel emptyState"><Sparkles size={34}/><h3>Your nearby feed starts with location</h3><p className="muted">Location is used only to find serviceable nearby inventory.</p><Link className="btn secondary" href="/market">Browse marketplace instead</Link></div>}<div className="grid storeGrid">{items.map(item=><Link className="card" href={`/market/${item.store_id}`} key={item.listing_id}><div className="row space"><span className="storeIcon"><ShoppingBag size={20}/></span><span className="pill">{item.distance_km.toFixed(1)} km</span></div><h3>{item.name}</h3><p className="muted">{item.brand?`${item.brand} • `:''}{item.unit}</p><strong>₹{item.price}</strong><div className="muted small">{item.store_name}</div><div className="muted small" style={{marginTop:6}}>{item.reason}</div></Link>)}</div></main></>;
}
