'use client';
import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,LocateFixed,MapPin,Search,XCircle} from 'lucide-react';
import {gaonApi,PlaceSuggestion,Serviceability} from '@/lib/api';
import {LocationMap} from '@/components/LocationMap';

const newSession=()=>typeof crypto!=='undefined'&&'randomUUID' in crypto?crypto.randomUUID():`${Date.now()}-${Math.random()}`;

export function AddressLocationPicker({latitude,longitude,onChange,onAddress}:{latitude?:number;longitude?:number;onChange:(lat:number,lng:number)=>void;onAddress:(address:string)=>void}){
 const[q,setQ]=useState('');const[suggestions,setSuggestions]=useState<PlaceSuggestion[]>([]);const[service,setService]=useState<Serviceability|null>(null);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const session=useRef(newSession());
 useEffect(()=>{if(q.trim().length<3){setSuggestions([]);return}const t=window.setTimeout(async()=>{try{setSuggestions(await gaonApi.placeAutocomplete(q.trim(),session.current));setMsg('')}catch(e:any){setSuggestions([]);setMsg(e.message||'Location search unavailable. You can still place the pin manually.')}},350);return()=>window.clearTimeout(t)},[q]);
 async function resolve(lat:number,lng:number){onChange(lat,lng);setSuggestions([]);try{const[s,r]=await Promise.all([gaonApi.serviceability(lat,lng),gaonApi.reverseGeocode(lat,lng)]);setService(s);if(r.formatted_address){onAddress(r.formatted_address);setQ(r.formatted_address)}}catch(e:any){setMsg(e.message||'Could not verify this location.')} }
 async function choose(item:PlaceSuggestion){setBusy(true);try{const r=await gaonApi.placeDetails(item.place_id,session.current);onChange(r.latitude,r.longitude);onAddress(r.formatted_address);setQ(r.formatted_address);setSuggestions([]);setService(await gaonApi.serviceability(r.latitude,r.longitude));session.current=newSession();setMsg('')}catch(e:any){setMsg(e.message||'Could not select this location.')}finally{setBusy(false)}}
 function current(){if(!navigator.geolocation){setMsg('Location is not supported by this browser.');return}setBusy(true);navigator.geolocation.getCurrentPosition(async p=>{await resolve(p.coords.latitude,p.coords.longitude);setBusy(false)},e=>{setMsg(e.message||'Location permission was denied.');setBusy(false)},{enableHighAccuracy:true,timeout:10000})}
 return <div className="stack"><div className="field"><label><Search size={15}/> Search delivery location</label><div className="row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search village, road, landmark or address" autoComplete="off"/><button type="button" className="btn secondary" onClick={current} disabled={busy}><LocateFixed size={16}/> Current location</button></div>{suggestions.length>0&&<div className="card stack" role="listbox">{suggestions.map(s=><button type="button" className="btn secondary" style={{justifyContent:'flex-start',textAlign:'left'}} key={s.place_id} onClick={()=>choose(s)}><MapPin size={16}/><span><strong>{s.main_text||s.text}</strong>{s.secondary_text&&<span className="muted small"> — {s.secondary_text}</span>}</span></button>)}</div>}</div><LocationMap latitude={latitude} longitude={longitude} editable onChange={resolve} height={300}/>{latitude!==undefined&&longitude!==undefined&&<span className="muted small">Pinned coordinates: {latitude.toFixed(5)}, {longitude.toFixed(5)}</span>}{service&&(service.serviceable?<div className="notice"><CheckCircle2 size={17}/> Delivery available in {service.service_area_name}. {service.distance_km!=null&&`About ${service.distance_km.toFixed(1)} km from the local hub.`}</div>:<div className="notice"><XCircle size={17}/> This pin is outside the currently active GaonOne delivery area. You can adjust the pin before saving.</div>)}{msg&&<div className="muted small">{msg}</div>}</div>
}