'use client';

import {FormEvent,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {gaonApi,setToken} from '@/lib/api';
import {Nav} from '@/components/Nav';

const defaults={merchant:'/merchant',admin:'/admin',delivery:'/delivery',customer:'/market'} as const;
function destination(role:keyof typeof defaults,next:string|null){if(!next||!next.startsWith('/')||next.startsWith('//'))return defaults[role];const allowed={customer:['/market','/cart','/orders','/account','/support','/updates'],merchant:['/merchant','/account','/support'],delivery:['/delivery','/account','/support'],admin:['/admin','/account']}[role];return allowed.some(prefix=>next===prefix||next.startsWith(`${prefix}/`))?next:defaults[role];}

export default function Login(){
  const[phone,setPhone]=useState('');const[name,setName]=useState('');const[otp,setOtp]=useState('');const[requestedPhone,setRequestedPhone]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[sessionPending,setSessionPending]=useState(false);const requestInFlight=useRef(false);const verifyInFlight=useRef(false);const router=useRouter();
  async function requestOtp(){if(requestInFlight.current)return;requestInFlight.current=true;setBusy(true);setMessage('');try{const result=await gaonApi.requestOtp(phone);setRequestedPhone(phone);setMessage(result.expires_in_seconds?`Code requested. It expires in ${Math.ceil(result.expires_in_seconds/60)} minutes.`:'Request accepted. SMS delivery and code expiry are controlled by the provider.');}catch(error:any){setMessage(error.message||'Could not request a code. Try again.')}finally{requestInFlight.current=false;setBusy(false)}}
  async function start(e:FormEvent){e.preventDefault();await requestOtp()}
  async function finishSession(){setBusy(true);setMessage('');try{const me=await gaonApi.me();const next=new URLSearchParams(window.location.search).get('next');router.replace(destination(me.role,next))}catch(error:any){setSessionPending(true);setMessage('Phone verified, but account details are temporarily unavailable. Retry without requesting another OTP.')}finally{setBusy(false)}}
  async function verify(e:FormEvent){e.preventDefault();if(verifyInFlight.current||sessionPending)return;verifyInFlight.current=true;setBusy(true);setMessage('');try{const result=await gaonApi.verifyOtp(requestedPhone,otp,name.trim()||undefined);setToken(result.access_token);setSessionPending(true);await finishSession()}catch(error:any){setMessage(error.message||'Could not verify the code. Try again.');setBusy(false)}finally{verifyInFlight.current=false}}
  function changeNumber(){setRequestedPhone('');setOtp('');setMessage('');setSessionPending(false)}
  return <><Nav/><div className="authWrap"><div className="panel authCard"><span className="eyebrow">Secure passwordless login</span><h1>Sign in with your mobile</h1><p className="muted">We will send a one-time code to your Indian mobile number.</p>{sessionPending?<div className="stack"><p>Your phone is verified. Continue the existing signed-in session.</p><button className="btn" disabled={busy} onClick={finishSession}>{busy?'Checking account…':'Continue signed-in session'}</button></div>:!requestedPhone?<form className="form" onSubmit={start}><label className="field" htmlFor="login-phone">Mobile number<input id="login-phone" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="10-digit mobile number" inputMode="tel" autoComplete="tel" required/></label><label className="field" htmlFor="login-name">Name <span className="muted">(optional)</span><input id="login-name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" autoComplete="name" maxLength={120}/></label><button className="btn" disabled={busy}>{busy?'Requesting code…':'Send OTP'}</button></form>:<form className="form" onSubmit={verify}><p>Code requested for <strong>{requestedPhone}</strong></p><label className="field" htmlFor="login-otp">One-time code<input id="login-otp" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,8))} inputMode="numeric" autoComplete="one-time-code" minLength={4} maxLength={8} required/></label><button className="btn" disabled={busy}>{busy?'Verifying…':'Verify & continue'}</button><div className="row"><button type="button" className="btn secondary" disabled={busy} onClick={requestOtp}>Resend code</button><button type="button" className="btn ghost" disabled={busy} onClick={changeNumber}>Change number</button></div><p className="muted small">Resend limits apply. GaonOne does not resend automatically.</p></form>}{message&&<p className="notice" role="status" aria-live="polite">{message}</p>}</div></div></>;
}
