'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {Clock3,MapPin,Minus,Plus,Search,ShoppingCart,Truck} from 'lucide-react';
import {gaonApi,Store,StoreProduct} from '@/lib/api';
import {Nav} from '@/components/Nav';

const money=(v:string|number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v));
export default function StorePage(){
  const {id}=useParams<{id:string}>();const [store,setStore]=useState<Store|null>(null);const [items,setItems]=useState<StoreProduct[]>([]);const [qty,setQty]=useState<Record<string,number>>({});const [q,setQ]=useState('');const [msg,setMsg]=useState('');const [cartCount,setCartCount]=useState(0);const [busy,setBusy]=useState('');
  useEffect(()=>{Promise.all([gaonApi.store(id),gaonApi.storeProducts(id)]).then(([s,p])=>{setStore(s);setItems(p)}).catch(e=>setMsg(e.message));gaonApi.cart().then(c=>setCartCount(c.items.reduce((a,i)=>a+i.quantity,0))).catch(()=>{})},[id]);
  const shown=useMemo(()=>items.filter(i=>{const text=`${i.product.name} ${i.product.brand||''} ${i.product.description||''}`.toLowerCase();return text.includes(q.toLowerCase())}),[items,q]);
  function amount(p:StoreProduct){return Math.min(qty[p.id]||1,p.stock_quantity)}
  async function add(p:StoreProduct){setBusy(p.id);try{const cart=await gaonApi.addCart(p.id,amount(p));setCartCount(cart.items.reduce((a,i)=>a+i.quantity,0));setMsg(`${amount(p)} × ${p.product.name} added to cart.`)}catch(e:any){setMsg(e.status===401?'Login with your phone to add items.':e.message)}finally{setBusy('')}}
  return <><Nav/><main className="container section">{store&&<div className="storeHero"><div><span className="eyebrow">Verified local storefront</span><h2>{store.name}</h2><p className="muted">{store.description||'Local essentials available from your village.'}</p><div className="row muted" style={{flexWrap:'wrap'}}>{store.landmark&&<span className="row"><MapPin size={15}/>{store.landmark}</span>}{(store.opens_at||store.closes_at)&&<span className="row"><Clock3 size={15}/>{store.opens_at?.slice(0,5)||'—'}–{store.closes_at?.slice(0,5)||'—'}</span>}{store.delivery_enabled&&<span className="row"><Truck size={15}/> Doorstep delivery</span>}</div></div><Link href="/cart" className="btn"><ShoppingCart size={17}/> Cart {cartCount>0&&`(${cartCount})`}</Link></div>}
  {msg&&<div className="notice">{msg}</div>}<div className="panel filterBar"><div className="search" style={{flex:1}}><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products in this store..."/></div><span className="badge">{shown.length} available</span></div>
  <div className="grid productGrid" style={{marginTop:20}}>{shown.map(p=>{const discount=p.mrp?Math.max(0,Math.round((1-Number(p.price)/Number(p.mrp))*100)):0;return <div className="card productCard" key={p.id}><div className="row space"><span className="pill">{p.product.unit}</span>{discount>0&&<span className="badge status-approved">{discount}% off</span>}</div><h3>{p.product.name}</h3><p className="muted clamp2">{p.product.brand||p.product.description||'Local catalogue item'}</p><div><span className="price">{money(p.price)}</span>{p.mrp&&Number(p.mrp)>Number(p.price)&&<span className="muted strike">{money(p.mrp)}</span>}</div><div className="row space" style={{marginTop:14}}><div className="qtyControl"><button className="qtyBtn" onClick={()=>setQty(x=>({...x,[p.id]:Math.max(1,amount(p)-1)}))}><Minus size={14}/></button><strong>{amount(p)}</strong><button className="qtyBtn" disabled={amount(p)>=p.stock_quantity} onClick={()=>setQty(x=>({...x,[p.id]:Math.min(p.stock_quantity,amount(p)+1)}))}><Plus size={14}/></button></div><button className="btn" disabled={busy===p.id} onClick={()=>add(p)}><ShoppingCart size={16}/> {busy===p.id?'Adding…':'Add'}</button></div><p className={`stockText ${p.stock_quantity<=5?'lowStock':''}`}>{p.stock_quantity<=5?`Only ${p.stock_quantity} left`:`${p.stock_quantity} in stock`}</p></div>})}</div>{shown.length===0&&<div className="panel emptyState"><h3>No matching products</h3><p className="muted">Try a different search term.</p></div>}</main></>;
}
