'use client';
import {useEffect,useState} from 'react';
import {RefreshCw,Timer,Truck} from 'lucide-react';
import {getToken} from '@/lib/api';
import {Nav} from '@/components/Nav';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
type Perf={window_days:number;target_minutes:number;total_deliveries:number;delivered:number;failed:number;active:number;failure_rate:number;on_time_rate?:number|null;avg_assign_to_pickup_minutes?:number|null;median_assign_to_pickup_minutes?:number|null;avg_pickup_to_delivery_minutes?:number|null;median_pickup_to_delivery_minutes?:number|null;avg_created_to_delivery_minutes?:number|null;median_created_to_delivery_minutes?:number|null;p90_created_to_delivery_minutes?:number|null};
const pct=(v?:number|null)=>v==null?'—':`${(v*100).toFixed(1)}%`;const mins=(v?:number|null)=>v==null?'—':`${v.toFixed(1)} min`;
export default function DeliveryPerformance(){const[data,setData]=useState<Perf|null>(null);const[error,setError]=useState('');async function load(){try{const token=getToken();if(!token)throw new Error('Login required');const r=await fetch(`${API}/admin/delivery-performance?window_days=30&target_minutes=90`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw new Error(`Delivery performance unavailable (${r.status})`);setData(await r.json());setError('')}catch(e:any){setError(e.message)}}useEffect(()=>{load()},[]);return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Operations intelligence</span><h2>Delivery performance</h2><p className="muted">30-day terminal-delivery performance. Active deliveries remain separate from failure and on-time rates.</p></div><button className="btn secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>{error&&<div className="notice">{error}</div>}{data&&<><div className="statsGrid"><div className="card statCard"><Truck/><span className="statValue">{data.delivered}</span><strong>Delivered</strong><span className="muted">{data.total_deliveries} total records</span></div><div className="card statCard"><span className="statValue">{data.failed}</span><strong>Failed</strong><span className="muted">Failure rate {pct(data.failure_rate)}</span></div><div className="card statCard"><span className="statValue">{data.active}</span><strong>Active</strong><span className="muted">Excluded from terminal rates</span></div><div className="card statCard"><Timer/><span className="statValue">{pct(data.on_time_rate)}</span><strong>On time</strong><span className="muted">Target ≤ {data.target_minutes} min</span></div></div><div className="panel"><h3>Timing distribution</h3><div className="metricRow"><span>Assign → pickup average</span><strong>{mins(data.avg_assign_to_pickup_minutes)}</strong></div><div className="metricRow"><span>Assign → pickup median</span><strong>{mins(data.median_assign_to_pickup_minutes)}</strong></div><div className="metricRow"><span>Pickup → delivery average</span><strong>{mins(data.avg_pickup_to_delivery_minutes)}</strong></div><div className="metricRow"><span>Pickup → delivery median</span><strong>{mins(data.median_pickup_to_delivery_minutes)}</strong></div><div className="metricRow"><span>Created → delivery median</span><strong>{mins(data.median_created_to_delivery_minutes)}</strong></div><div className="metricRow"><span>Created → delivery P90</span><strong>{mins(data.p90_created_to_delivery_minutes)}</strong></div></div></>}</main></>}
