'use client';
import {useEffect,useState} from 'react';
import {BarChart3,RefreshCw,TrendingDown,TrendingUp} from 'lucide-react';
import {api,gaonApi,Store} from '@/lib/api';
import {Nav} from '@/components/Nav';

type ForecastProduct={store_product_id:string;product_name:string;unit:string;stock_quantity:number;sold_recent_7d:number;forecast_units:number;safety_stock_units:number;recommended_reorder_units:number;trend:string;confidence:string;recommendation:string;reason:string};
type Forecast={store_id:string;window_days:number;horizon_days:number;method:string;products:ForecastProduct[]};
export default function MerchantInsights(){const[stores,setStores]=useState<Store[]>([]);const[storeId,setStoreId]=useState('');const[data,setData]=useState<Forecast|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(false);useEffect(()=>{gaonApi.myStores().then(s=>{setStores(s);if(s[0])setStoreId(s[0].id)}).catch(e=>setError(e.message))},[]);useEffect(()=>{if(storeId)load()},[storeId]);async function load(){setLoading(true);try{setData(await api<Forecast>(`/merchant/stores/${storeId}/demand-forecast?window_days=28&horizon_days=7`));setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Merchant intelligence</span><h2>7-day demand outlook</h2><p className="muted">Transparent sales-velocity guidance. Recommendations never change stock automatically.</p></div><button className="btn secondary" onClick={load} disabled={!storeId||loading}><RefreshCw size={16}/> Refresh</button></div>{error&&<div className="notice">{error}</div>}<div className="panel"><label htmlFor="forecast-store"><strong>Store</strong></label><select id="forecast-store" value={storeId} onChange={e=>setStoreId(e.target.value)}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{data&&<><div className="notice"><BarChart3 size={18}/> Forecast method: <strong>{data.method.replaceAll('_',' ')}</strong> • {data.window_days}-day history → {data.horizon_days}-day outlook.</div><div className="panel tableWrap"><table className="table"><thead><tr><th>Product</th><th>Stock</th><th>7d sold</th><th>Forecast</th><th>Trend</th><th>Confidence</th><th>Action</th></tr></thead><tbody>{data.products.map(p=><tr key={p.store_product_id}><td><strong>{p.product_name}</strong><div className="muted small">{p.unit}</div></td><td>{p.stock_quantity}</td><td>{p.sold_recent_7d}</td><td>{p.forecast_units} + {p.safety_stock_units} safety</td><td><span className="row">{p.trend==='rising'?<TrendingUp size={15}/>:p.trend==='falling'?<TrendingDown size={15}/>:null}{p.trend.replaceAll('_',' ')}</span></td><td>{p.confidence}</td><td><strong>{p.recommendation==='reorder'?`Reorder ${p.recommended_reorder_units}`:p.recommendation}</strong><div className="muted small">{p.reason}</div></td></tr>)}</tbody></table></div></>}</main></>}
