'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Minus,Plus,ShoppingBag,Trash2} from 'lucide-react';
import {gaonApi,Cart} from '@/lib/api';
import {Nav} from '@/components/Nav';
const money=(v:string|number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v));
export default function CartPage(){
 const[cart,setCart]=useState<Cart|null>(null);const[err,setErr]=useState('');const[busy,setBusy]=useState('');
 async function load(){try{setCart(await gaonApi.cart());setErr('')}catch(e:any){setErr(e.message)}}
 useEffect(()=>{load()},[]);
 async function qty(id:string,n:number){setBusy(id);try{if(n<=0)await gaonApi.removeCart(id);else await gaonApi.addCart(id,n);await load()}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 async function clear(){if(!confirm('Clear all items from your cart?'))return;try{setCart(await gaonApi.clearCart())}catch(e:any){setErr(e.message)}}
 return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Basket</span><h2>Your cart</h2><p className="muted">Review quantities before checkout.</p></div>{cart?.items.length?<button className="btn ghost dangerText" onClick={clear}><Trash2 size={16}/> Clear cart</button>:null}</div>{err&&<div className="notice">{err}</div>}{cart?.items.length?<div className="splitGrid cartLayout"><div className="panel"><div className="stack">{cart.items.map(i=><div className="cartItem" key={i.id}><div><strong>{i.store_product.product.name}</strong><div className="muted">{money(i.store_product.price)} • {i.store_product.product.unit}</div><div className="muted small">{i.store_product.stock_quantity} currently in stock</div></div><div className="row"><div className="qtyControl"><button className="qtyBtn" disabled={busy===i.store_product_id} onClick={()=>qty(i.store_product_id,i.quantity-1)}><Minus size={14}/></button><strong>{i.quantity}</strong><button className="qtyBtn" disabled={busy===i.store_product_id||i.quantity>=i.store_product.stock_quantity} onClick={()=>qty(i.store_product_id,i.quantity+1)}><Plus size={14}/></button></div><strong className="lineTotal">{money(Number(i.store_product.price)*i.quantity)}</strong></div></div>)}</div></div><aside className="panel summaryCard"><h3>Order summary</h3><div className="metricRow"><span>Items subtotal</span><strong>{money(cart.subtotal)}</strong></div><div className="metricRow"><span>Delivery &amp; final total</span><strong>Calculated at checkout</strong></div><p className="muted small">Select a delivery address at checkout for the backend-authoritative fee and total. Stock and pricing are revalidated when you place the order.</p><Link className="btn fullBtn" href="/checkout">Continue to checkout</Link><Link className="btn secondary fullBtn" href="/market">Keep shopping</Link></aside></div>:<div className="panel emptyState"><ShoppingBag size={40}/><h3>Your cart is empty</h3><p className="muted">Choose a nearby store and add local essentials.</p><Link className="btn" href="/market">Explore marketplace</Link></div>}</main></>
}
