'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,Clock3,Minus,Plus,ShoppingBag,Trash2} from 'lucide-react';
import {gaonApi,Cart,CartHealth} from '@/lib/api';
import {PreparationEstimate,preparationCopy,preparationEstimate} from '@/lib/commerceIntelligence';
import {Nav} from '@/components/Nav';
const money=(v:string|number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v));
export default function CartPage(){
 const [cart,setCart]=useState<Cart|null>(null);const[health,setHealth]=useState<CartHealth|null>(null);const[prep,setPrep]=useState<PreparationEstimate|null>(null);const[err,setErr]=useState('');const[busy,setBusy]=useState('');
 async function load(){try{const[c,h]=await Promise.all([gaonApi.cart(),gaonApi.cartHealth()]);setCart(c);setHealth(h);setErr('');if(c.store_id){preparationEstimate(c.store_id).then(setPrep).catch(()=>setPrep(null))}else setPrep(null)}catch(e:any){setErr(e.message)}}
 useEffect(()=>{load()},[]);
 async function qty(id:string,n:number){setBusy(id);try{if(n<=0)await gaonApi.removeCart(id);else await gaonApi.addCart(id,n);await load()}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 async function clear(){if(!confirm('Clear all items from your cart?'))return;try{setCart(await gaonApi.clearCart());setHealth(await gaonApi.cartHealth());setPrep(null)}catch(e:any){setErr(e.message)}}
 const blocked=health?.status==='blocked';
 return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Basket</span><h2>Your cart</h2><p className="muted">Live stock health is checked before checkout.</p></div>{cart?.items.length?<button className="btn ghost dangerText" onClick={clear}><Trash2 size={16}/> Clear cart</button>:null}</div>
 {err&&<div className="notice">{err}</div>}
 {health&&health.status!=='empty'&&<div className={`notice ${blocked?'dangerText':''}`}><div className="row">{blocked?<AlertTriangle size={18}/>:<CheckCircle2 size={18}/>}<strong>{blocked?'Cart needs attention':health.status==='warning'?'Almost ready':'Cart ready for checkout'}</strong></div>{blocked&&<div className="muted small">One or more items no longer have enough stock. Adjust quantities before continuing.</div>}{health.status==='warning'&&<div className="muted small">Some items are running low. Checkout soon to improve fulfilment confidence.</div>}</div>}
 {prep&&<div className="notice"><div className="row"><Clock3 size={18}/><strong>{preparationCopy(prep)}</strong></div><div className="muted small">Store preparation estimate; delivery travel time is separate.</div></div>}
 {cart?.items.length?<div className="splitGrid cartLayout"><div className="panel"><div className="stack">{cart.items.map(i=>{const hi=health?.items.find(h=>h.listing_id===i.store_product_id);return <div className="cartItem" key={i.id}><div><strong>{i.store_product.product.name}</strong><div className="muted">{money(i.store_product.price)} • {i.store_product.product.unit}</div><div className="muted small">{i.store_product.stock_quantity} currently in stock{hi?.state==='blocked'?' • quantity unavailable':hi?.state==='warning'?' • low stock':''}</div></div><div className="row"><div className="qtyControl"><button className="qtyBtn" disabled={busy===i.store_product_id} onClick={()=>qty(i.store_product_id,i.quantity-1)}><Minus size={14}/></button><strong>{i.quantity}</strong><button className="qtyBtn" disabled={busy===i.store_product_id||i.quantity>=i.store_product.stock_quantity} onClick={()=>qty(i.store_product_id,i.quantity+1)}><Plus size={14}/></button></div><strong className="lineTotal">{money(Number(i.store_product.price)*i.quantity)}</strong></div></div>})}</div></div><aside className="panel summaryCard"><h3>Order summary</h3><div className="metricRow"><span>Items subtotal</span><strong>{money(cart.subtotal)}</strong></div><div className="metricRow"><span>Delivery & final total</span><strong>Calculated at checkout</strong></div><p className="muted small">The checkout decision is authoritative for delivery fee, serviceability and total. Inventory is revalidated again before the order is placed.</p>{blocked?<button className="btn fullBtn" disabled>Resolve cart issues</button>:<Link className="btn fullBtn" href="/checkout">Continue to checkout</Link>}<Link className="btn secondary fullBtn" href="/market">Keep shopping</Link></aside></div>:<div className="panel emptyState"><ShoppingBag size={40}/><h3>Your cart is empty</h3><p className="muted">Choose a nearby store and add local essentials.</p><Link className="btn" href="/market">Explore marketplace</Link></div>}</main></>;
}
