'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Clock3,LocateFixed,MapPin,Search,ShoppingBag,Store as StoreIcon,Truck} from 'lucide-react';
import {gaonApi,NearbyStore,Store,Village} from '@/lib/api';
import {Nav} from '@/components/Nav';
import {UniversalLocationSearch} from '@/components/UniversalLocationSearch';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
type DiscoveryProduct={listing_id:string;product_id:string;store_id:string;store_name:string;name:string;brand?:string;unit:string;price:string;mrp?:string;distance_km:number;match_score:number};
type DiscoveryStore={id:string;name:string;landmark?:string;delivery_enabled:boolean;distance_km:number;match_score:number};
type DiscoveryResult={query:string;stores:DiscoveryStore[];products:DiscoveryProduct[];categories:{id:string;name:string;slug:string;available_listing_count:number}[]};

export default function Market(){
  const [villages,setVillages]=useState<Village[]>([]);const [stores,setStores]=useState<(Store|NearbyStore)[]>([]);const [v,setV]=useState('');const [q,setQ]=useState('');const [delivery,setDelivery]=useState(false);const [nearby,setNearby]=useState(false);const [locationLabel,setLocationLabel]=useState('');const [latitude,setLatitude]=useState<number|null>(null);const [longitude,setLongitude]=useState<number|null>(null);const [serviceable,setServiceable]=useState<boolean|null>(null);const [serviceArea,setServiceArea]=useState('');const [products,setProducts]=useState<DiscoveryProduct[]>([]);const [searching,setSearching]=useState(false);const [loading,setLoading]=useState(false);const [msg,setMsg]=useState('');const [urlResolved,setUrlResolved]=useState(false);
  useEffect(()=>{gaonApi.villages().then(setVillages).catch(e=>setMsg(e.message))},[]);
  useEffect(()=>{if(typeof window==='undefined'||urlResolved)return;const params=new URLSearchParams(window.location.search);const lat=Number(params.get('lat'));const lng=Number(params.get('lng'));const label=params.get('location')||'';if(Number.isFinite(lat)&&Number.isFinite(lng)&&params.has('lat')&&params.has('lng')){setLatitude(lat);setLongitude(lng);setLocationLabel(label);setServiceable(params.get('serviceable')==='1'?true:params.get('serviceable')==='0'?false:null);setServiceArea(params.get('service_area')||'');setNearby(true);setV('')}setUrlResolved(true)},[urlResolved]);
  useEffect(()=>{if(!urlResolved)return;if(nearby&&latitude!=null&&longitude!=null){setLoading(true);gaonApi.nearbyStores(latitude,longitude,20,delivery||undefined).then(data=>{setStores(data);setMsg(data.length?`Showing places near ${locationLabel||'your selected location'}.`:`No active stores found near ${locationLabel||'this location'} yet.`)}).catch(e=>setMsg(e.message)).finally(()=>setLoading(false));return}setLoading(true);gaonApi.stores(v||undefined,q||undefined,delivery||undefined).then(setStores).catch(e=>setMsg(e.message)).finally(()=>setLoading(false))},[v,delivery,nearby,urlResolved,latitude,longitude,locationLabel]);
  useEffect(()=>{if(!nearby||latitude==null||longitude==null||q.trim().length<1){setProducts([]);return}const controller=new AbortController();const timer=setTimeout(async()=>{setSearching(true);try{const params=new URLSearchParams({q:q.trim(),latitude:String(latitude),longitude:String(longitude),radius_km:'20'});const response=await fetch(`${API}/discovery/search?${params}`,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error('Nearby search is temporarily unavailable.');const data:DiscoveryResult=await response.json();setProducts(data.products);const matchedIds=new Set(data.stores.map(s=>s.id));if(data.stores.length)setStores(current=>current.filter(s=>matchedIds.has(s.id)||data.products.some(p=>p.store_id===s.id)))}catch(e){if((e as Error).name!=='AbortError')setMsg((e as Error).message)}finally{setSearching(false)}},250);return()=>{clearTimeout(timer);controller.abort()}},[q,nearby,latitude,longitude]);
  async function useLocation(){if(!navigator.geolocation){setMsg('Location is not supported by this browser.');return}setLoading(true);navigator.geolocation.getCurrentPosition(async pos=>{setLatitude(pos.coords.latitude);setLongitude(pos.coords.longitude);setNearby(true);setV('');setLocationLabel('Current location');setServiceable(null);setServiceArea('');setLoading(false)},()=>{setLoading(false);setMsg('Location permission was not granted. Search for an area, colony, city, village, landmark or pincode instead.')},{enableHighAccuracy:false,timeout:10000})}
  const shown=useMemo(()=>nearby?stores:stores.filter(s=>!q||s.name.toLowerCase().includes(q.toLowerCase())||(s.description||'').toLowerCase().includes(q.toLowerCase())),[stores,q,nearby]);
  function clearLocation(){setNearby(false);setLatitude(null);setLongitude(null);setLocationLabel('');setServiceable(null);setServiceArea('');setProducts([]);setMsg('')}
  return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Local marketplace</span><h2>What’s available around you?</h2><p className="muted">Search any area—from a city colony to a village landmark—and see what GaonOne can fulfil nearby.</p></div><button className="btn secondary" onClick={useLocation}><LocateFixed size={17}/> Near me</button></div>
  {serviceable===false&&<div className="notice"><strong>We’re not fully live at this exact point yet.</strong> {serviceArea?`Nearest active GaonOne service area: ${serviceArea}. `:''}You can still browse nearby availability while coverage expands.</div>}
  {serviceable===true&&serviceArea&&<div className="notice">Serviceable through <strong>{serviceArea}</strong>.</div>}
  {msg&&<div className="notice">{msg}</div>}
  <div className="panel" style={{marginBottom:14}}><UniversalLocationSearch compact/>{nearby&&locationLabel&&<div className="row muted" style={{marginTop:10}}><MapPin size={15}/><strong>{locationLabel}</strong></div>}</div>
  <div className="panel filterBar"><div className="search" style={{flex:1,minWidth:220}}><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={nearby?'Search food, groceries, products or stores nearby...':'Search stores or essentials...'}/></div><select value={v} onChange={e=>{setV(e.target.value);clearLocation()}}><option value="">All service areas</option>{villages.map(x=><option value={x.id} key={x.id}>{x.name}, {x.district}</option>)}</select><label className="toggleRow"><input type="checkbox" checked={delivery} onChange={e=>setDelivery(e.target.checked)}/><Truck size={16}/> Delivery only</label></div>
  {nearby&&q.trim()&&<div style={{marginTop:18}}><div className="row space"><strong>{searching?'Searching nearby inventory…':`${products.length} product${products.length===1?'':'s'} matched nearby`}</strong></div>{products.length>0&&<div className="grid storeGrid" style={{marginTop:10}}>{products.slice(0,12).map(p=><Link className="card" href={`/market/${p.store_id}`} key={p.listing_id}><div className="row space"><span className="storeIcon"><ShoppingBag size={20}/></span><span className="pill">{p.distance_km.toFixed(1)} km</span></div><h3>{p.name}</h3><p className="muted">{p.brand?`${p.brand} • `:''}{p.unit}</p><strong>₹{p.price}</strong><div className="muted" style={{marginTop:8}}>{p.store_name}</div></Link>)}</div>}</div>}
  <div className="row space" style={{margin:'18px 0'}}><strong>{loading?'Loading stores…':`${shown.length} store${shown.length===1?'':'s'} found`}</strong>{nearby&&<button className="btn ghost" onClick={clearLocation}>Clear location filter</button>}</div>
  <div className="grid storeGrid">{shown.map(s=>{const distance='distance_km'in s?s.distance_km:null;return <Link className="card storeCard" href={`/market/${s.id}`} key={s.id}><div className="row space"><span className="storeIcon"><StoreIcon size={22}/></span><div className="row">{s.delivery_enabled&&<span className="pill"><Truck size={13}/> Delivery</span>}{s.pickup_enabled&&<span className="pill">Pickup</span>}</div></div><h3>{s.name}</h3><p className="muted clamp2">{s.description||'Verified local store serving this area.'}</p><div className="stack compact"><div className="row muted"><MapPin size={15}/>{s.landmark||'Local market'}{distance!==null&&<strong> • {distance} km</strong>}</div>{(s.opens_at||s.closes_at)&&<div className="row muted"><Clock3 size={15}/>{s.opens_at?.slice(0,5)||'—'} – {s.closes_at?.slice(0,5)||'—'}</div>}</div><span className="cardLink">View store →</span></Link>})}</div>{!loading&&shown.length===0&&products.length===0&&<div className="panel emptyState"><StoreIcon size={34}/><h3>No live availability found here yet</h3><p className="muted">Try another nearby area, landmark, town, city, village or pincode, or remove the delivery filter.</p></div>}</main></>;
}
