'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {RefreshCw,Truck} from 'lucide-react';
import {api,gaonApi,Order,OrderDetail} from '@/lib/api';
import {Nav} from '@/components/Nav';

type Event={id:string;entity_type:string;from_status:string;to_status:string;reason?:string;created_at:string};
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function OrderLifecycle(){const[orders,setOrders]=useState<Order[]>([]);const[selected,setSelected]=useState('');const[detail,setDetail]=useState<OrderDetail|null>(null);const[events,setEvents]=useState<Event[]>([]);const[error,setError]=useState('');async function loadOrders(){try{const rows=await gaonApi.orders();setOrders(rows);if(!selected&&rows[0])setSelected(rows[0].id);setError('')}catch(e:any){setError(e.message)}}async function loadOrder(id:string){if(!id)return;try{const[d,e]=await Promise.all([gaonApi.order(id),api<Event[]>(`/orders/${id}/events`)]);setDetail(d);setEvents(e);setError('')}catch(e:any){setError(e.message)}}useEffect(()=>{loadOrders()},[]);useEffect(()=>{loadOrder(selected)},[selected]);return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Customer lifecycle</span><h2>Order journey</h2><p className="muted">Backend-authoritative order and delivery transitions, including live tracking when active.</p></div><button className="btn secondary" onClick={()=>{loadOrders();loadOrder(selected)}}><RefreshCw size={16}/> Refresh</button></div>{error&&<div className="notice">{error}</div>}<div className="splitGrid"><div className="panel"><h3>Your orders</h3><div className="stack">{orders.map(o=><button key={o.id} className={`card ${selected===o.id?'selected':''}`} onClick={()=>setSelected(o.id)} style={{textAlign:'left'}}><strong>{o.order_number}</strong><div className="row"><span className={`badge status-${o.status}`}>{label(o.status)}</span><span className="muted small">{o.payment_method.toUpperCase()} · {label(o.payment_status)}</span></div></button>)}</div></div><div className="panel">{detail?<><div className="row space"><div><span className="eyebrow">{detail.order_number}</span><h3>{label(detail.status)}</h3></div><Link className="btn secondary" href="/orders">Full order</Link></div><div className="stack" style={{marginTop:16}}>{events.map(e=><div className="card" key={e.id}><div className="row space"><strong>{label(e.to_status)}</strong><span className="muted small">{new Date(e.created_at).toLocaleString('en-IN')}</span></div><p className="muted small">{label(e.entity_type)}: {label(e.from_status)} → {label(e.to_status)}</p>{e.reason&&<p className="small">{e.reason}</p>}</div>)}{events.length===0&&<div className="emptyState"><Truck size={32}/><p className="muted">No transition events recorded yet.</p></div>}</div></>:<p className="muted">Select an order.</p>}</div></div></main></>}
