'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {Boxes,Clock3,PackageCheck,RefreshCw,Store as StoreIcon,Truck} from 'lucide-react';
import {gaonApi,Merchant,Order,Product,ServiceArea,Store,StoreProduct,Village} from '@/lib/api';
import {AddressLocationPicker} from '@/components/AddressLocationPicker';
import {Nav} from '@/components/Nav';

const money=(v:string|number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v));
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function MerchantPage(){
 const[m,setM]=useState<Merchant|null>(null);const[stores,setStores]=useState<Store[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[products,setProducts]=useState<Product[]>([]);const[inventory,setInventory]=useState<StoreProduct[]>([]);const[villages,setVillages]=useState<Village[]>([]);const[areas,setAreas]=useState<ServiceArea[]>([]);const[err,setErr]=useState('');const[business,setBusiness]=useState('');const[storeName,setStoreName]=useState('');const[village,setVillage]=useState('');const[area,setArea]=useState('');const[landmark,setLandmark]=useState('');const[phone,setPhone]=useState('');const[description,setDescription]=useState('');const[opens,setOpens]=useState('08:00');const[closes,setCloses]=useState('21:00');const[storeLat,setStoreLat]=useState<number|undefined>();const[storeLng,setStoreLng]=useState<number|undefined>();const[product,setProduct]=useState('');const[price,setPrice]=useState('');const[mrp,setMrp]=useState('');const[stock,setStock]=useState('10');const[storeId,setStoreId]=useState('');const[busy,setBusy]=useState('');
 async function load(){try{const me=await gaonApi.merchant();setM(me);const[own,os,ps,vs,serviceAreas]=await Promise.all([gaonApi.myStores(),gaonApi.merchantOrders(),gaonApi.products(),gaonApi.villages(),gaonApi.serviceAreas()]);setStores(own);setStoreId(x=>x||own[0]?.id||'');setOrders(os);setProducts(ps);setVillages(vs);setAreas(serviceAreas);setErr('')}catch(e:any){setErr(e.message)}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(storeId)gaonApi.storeInventory(storeId).then(setInventory).catch(e=>setErr(e.message));else setInventory([])},[storeId]);
 const openOrders=useMemo(()=>orders.filter(o=>!['delivered','cancelled'].includes(o.status)),[orders]);const lowStock=useMemo(()=>inventory.filter(i=>i.stock_quantity<=5).length,[inventory]);
 async function apply(e:FormEvent){e.preventDefault();try{await gaonApi.applyMerchant(business);location.reload()}catch(e:any){setErr(e.message)}}
 async function createStore(e:FormEvent){e.preventDefault();try{if(storeLat===undefined||storeLng===undefined){setErr('Pin the exact storefront entrance before creating the store.');return}const service=await gaonApi.serviceability(storeLat,storeLng);if(!service.serviceable){setErr('This storefront is outside the active GaonOne service area. Adjust the pin before creating it.');return}const slug=storeName.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-5);await gaonApi.createStore({village_id:village,service_area_id:area||service.service_area_id||null,name:storeName,slug,landmark,phone:phone||undefined,description:description||undefined,latitude:storeLat,longitude:storeLng,opens_at:`${opens}:00`,closes_at:`${closes}:00`,delivery_enabled:true,pickup_enabled:true});setStoreName('');setLandmark('');setPhone('');setDescription('');setStoreLat(undefined);setStoreLng(undefined);setArea('');await load()}catch(e:any){setErr(e.message)}}
 async function saveListing(e:FormEvent){e.preventDefault();try{await gaonApi.addListing(storeId,{product_id:product,price:Number(price),mrp:mrp?Number(mrp):null,stock_quantity:Number(stock),is_available:Number(stock)>0});setPrice('');setMrp('');setProduct('');setInventory(await gaonApi.storeInventory(storeId))}catch(e:any){setErr(e.message)}}
 async function editListing(item:StoreProduct,patch:{stock_quantity?:number;is_available?:boolean}){setBusy(item.id);try{await gaonApi.addListing(item.store_id,{product_id:item.product_id,price:Number(item.price),mrp:item.mrp?Number(item.mrp):null,stock_quantity:patch.stock_quantity??item.stock_quantity,is_available:patch.is_available??item.is_available});setInventory(await gaonApi.storeInventory(storeId))}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 async function toggleStore(s:Store){setBusy(s.id);try{await gaonApi.updateStore(s.id,{is_active:!s.is_active});await load()}catch(e:any){setErr(e.message)}finally{setBusy('')}}async function status(id:string,next:string){setBusy(id);try{await gaonApi.updateMerchantOrder(id,next);await load()}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 if(!m)return <><Nav/><main className="container section"><div className="panel authCard"><span className="eyebrow">Merchant onboarding</span><h2>List your local business</h2><p className="muted">Create a merchant profile. Your storefront can go live after admin approval.</p>{err&&<div className="notice">{err}</div>}<form className="form" onSubmit={apply}><div className="field"><label htmlFor="merchant-business">Business name</label><input id="merchant-business" required value={business} onChange={e=>setBusiness(e.target.value)} placeholder="e.g. Patil Kirana"/></div><button className="btn">Submit merchant application</button></form></div></main></>;
 return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Merchant console</span><h2>{m.business_name}</h2><p className="muted">Operate storefronts, stock and fulfilment from one place.</p></div><div className="row"><span className={`badge status-${m.status}`}>{label(m.status)}</span><button className="btn secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div></div>{err&&<div className="notice">{err}</div>}
 {m.status==='suspended'&&<div className="panel"><h3>Merchant access suspended</h3><p className="muted">Your stores are hidden from customers until an administrator reactivates the business.</p></div>}{m.status==='pending'&&<div className="panel"><h3>Approval pending</h3><p className="muted">Your business application has been recorded. Store operations become available after review.</p></div>}
 {m.status==='approved'&&<><div className="statsGrid"><div className="card statCard"><StoreIcon/><span className="statValue">{stores.length}</span><strong>Stores</strong><span className="muted">{stores.filter(s=>s.is_active).length} live</span></div><div className="card statCard"><Boxes/><span className="statValue">{inventory.length}</span><strong>Listings</strong><span className="muted">Selected store</span></div><div className="card statCard"><Clock3/><span className="statValue">{openOrders.length}</span><strong>Open orders</strong><span className="muted">Require fulfilment</span></div><div className="card statCard"><PackageCheck/><span className="statValue">{lowStock}</span><strong>Low stock</strong><span className="muted">5 units or less</span></div></div>
 <section className="section splitGrid"><div className="panel"><h3>Create storefront</h3><form className="form" onSubmit={createStore}>
 <div className="field"><label htmlFor="store-name">Store name</label><input id="store-name" required value={storeName} onChange={e=>setStoreName(e.target.value)}/></div>
 <div className="field"><label htmlFor="store-description">Description</label><textarea id="store-description" value={description} onChange={e=>setDescription(e.target.value)} placeholder="What customers can buy here"/></div>
 <div className="row"><div className="field" style={{flex:1}}><label htmlFor="store-village">Area / locality</label><select id="store-village" required value={village} onChange={e=>{setVillage(e.target.value);const v=villages.find(x=>x.id===e.target.value);if(v?.latitude!==undefined&&v?.longitude!==undefined){setStoreLat(v.latitude);setStoreLng(v.longitude)}}}><option value="">Select area / locality</option>{villages.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></div><div className="field" style={{flex:1}}><label htmlFor="store-service-area">Service area</label><select id="store-service-area" value={area} onChange={e=>setArea(e.target.value)}><option value="">Auto-detect from pin</option>{areas.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></div></div>
 <div className="field"><label htmlFor="store-landmark">Landmark / resolved address</label><input id="store-landmark" value={landmark} onChange={e=>setLandmark(e.target.value)} placeholder="Near bus stand, temple, market..."/></div>
 <div className="field"><div className="fieldLabel">Exact storefront entrance *</div><AddressLocationPicker mode="store" latitude={storeLat} longitude={storeLng} onChange={(lat,lng)=>{setStoreLat(lat);setStoreLng(lng)}} onAddress={setLandmark} onServiceability={service=>{if(service?.serviceable&&service.service_area_id)setArea(service.service_area_id)}}/></div>
 <div className="field"><label htmlFor="store-phone">Store phone</label><input id="store-phone" value={phone} onChange={e=>setPhone(e.target.value)}/></div>
 <div className="row"><div className="field" style={{flex:1}}><label htmlFor="store-opens">Opens</label><input id="store-opens" type="time" value={opens} onChange={e=>setOpens(e.target.value)}/></div><div className="field" style={{flex:1}}><label htmlFor="store-closes">Closes</label><input id="store-closes" type="time" value={closes} onChange={e=>setCloses(e.target.value)}/></div></div><button className="btn">Create store</button></form></div>
 <div className="panel"><h3>Your storefronts</h3><div className="stack">{stores.map(s=><div className="card" key={s.id}><div className="row space"><div><strong>{s.name}</strong><div className="muted">{s.landmark||'No landmark'} • {s.opens_at?.slice(0,5)||'—'}–{s.closes_at?.slice(0,5)||'—'}</div>{s.latitude!==undefined&&s.longitude!==undefined&&<div className="muted small">Exact map location saved</div>}</div><span className={`badge ${s.is_active?'status-approved':'status-suspended'}`}>{s.is_active?'Live':'Paused'}</span></div><div className="row" style={{marginTop:12}}><button className="btn secondary" onClick={()=>setStoreId(s.id)}>Manage inventory</button><button className="btn ghost" disabled={busy===s.id} onClick={()=>toggleStore(s)}>{s.is_active?'Pause store':'Go live'}</button></div></div>)}{stores.length===0&&<span className="muted">Create your first store to begin selling.</span>}</div></div></section>
 {stores.length>0&&<section className="section splitGrid"><div className="panel"><h3>Add / update inventory</h3><form className="form" onSubmit={saveListing}>
 <div className="field"><label htmlFor="inventory-store">Store</label><select id="inventory-store" required value={storeId} onChange={e=>setStoreId(e.target.value)}>{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div>
 <div className="field"><label htmlFor="inventory-product">Product</label><select id="inventory-product" required value={product} onChange={e=>setProduct(e.target.value)}><option value="">Select product</option>{products.map(p=><option value={p.id} key={p.id}>{p.name} • {p.unit}</option>)}</select></div>
 <div className="row"><div className="field" style={{flex:1}}><label htmlFor="inventory-price">Selling price ₹</label><input id="inventory-price" type="number" min="1" step="0.01" required value={price} onChange={e=>setPrice(e.target.value)}/></div><div className="field" style={{flex:1}}><label htmlFor="inventory-mrp">MRP ₹</label><input id="inventory-mrp" type="number" min="1" step="0.01" value={mrp} onChange={e=>setMrp(e.target.value)}/></div><div className="field" style={{flex:1}}><label htmlFor="inventory-stock">Stock</label><input id="inventory-stock" type="number" min="0" required value={stock} onChange={e=>setStock(e.target.value)}/></div></div><button className="btn">Save inventory</button></form></div><div className="panel"><div className="row space"><h3>Inventory</h3><span className="badge">{inventory.length} SKUs</span></div><div className="tableWrap"><table className="table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>State</th><th>Action</th></tr></thead><tbody>{inventory.map(i=><tr key={i.id}><td><strong>{i.product.name}</strong><div className="muted">{i.product.unit}</div></td><td>{money(i.price)}</td><td><div className="row"><button className="qtyBtn" aria-label={`Decrease ${i.product.name} stock`} disabled={busy===i.id||i.stock_quantity===0} onClick={()=>editListing(i,{stock_quantity:Math.max(0,i.stock_quantity-1)})}>−</button><strong>{i.stock_quantity}</strong><button className="qtyBtn" aria-label={`Increase ${i.product.name} stock`} disabled={busy===i.id} onClick={()=>editListing(i,{stock_quantity:i.stock_quantity+1,is_available:true})}>+</button></div></td><td><span className={`badge ${i.is_available?'status-approved':'status-suspended'}`}>{i.is_available?'Available':'Hidden'}</span></td><td><button className="btn ghost" disabled={busy===i.id} onClick={()=>editListing(i,{is_available:!i.is_available})}>{i.is_available?'Hide':'Show'}</button></td></tr>)}{inventory.length===0&&<tr><td colSpan={5} className="muted">No inventory in this store yet.</td></tr>}</tbody></table></div></div></section>}
 <section className="section"><div className="panel"><div className="row space"><div><h3>Order fulfilment</h3><span className="muted">Accept → prepare → ready for rider.</span></div><span className="badge">{openOrders.length} active</span></div><div className="stack" style={{marginTop:14}}>{orders.map(o=><div className="card row space" key={o.id}><div><strong>{o.order_number}</strong><div className="muted">{money(o.total)} • {label(o.status)} • {new Date(o.created_at).toLocaleString('en-IN')}</div></div><div className="row">{o.status==='placed'&&<><button className="btn" disabled={busy===o.id} onClick={()=>status(o.id,'accepted')}>Accept</button><button className="btn dangerBtn" disabled={busy===o.id} onClick={()=>status(o.id,'cancelled')}>Reject</button></>}{o.status==='accepted'&&<><button className="btn" disabled={busy===o.id} onClick={()=>status(o.id,'preparing')}>Start preparing</button><button className="btn dangerBtn" disabled={busy===o.id} onClick={()=>status(o.id,'cancelled')}>Cancel</button></>}{o.status==='preparing'&&<button className="btn" disabled={busy===o.id} onClick={()=>status(o.id,'ready')}>Ready for rider</button>}{o.status==='ready'&&<span className="badge"><Truck size={13}/> Waiting for rider</span>}{['out_for_delivery','delivered','cancelled'].includes(o.status)&&<span className={`badge status-${o.status}`}>{label(o.status)}</span>}</div></div>)}{orders.length===0&&<span className="muted">No merchant orders yet.</span>}</div></div></section></>}</main></>;
}
