'use client';
import Link from 'next/link';
import {useState} from 'react';
import {MapPin,Search} from 'lucide-react';
import {getToken} from '@/lib/api';
import {Nav} from '@/components/Nav';

type Suggestion={kind:string;label:string;secondary?:string|null;store_id?:string|null;distance_km?:number|null};
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
export default function NearbySearch(){const[q,setQ]=useState('');const[items,setItems]=useState<Suggestion[]>([]);const[msg,setMsg]=useState('Search products, stores or categories around your current location.');const[busy,setBusy]=useState(false);async function search(value:string){setQ(value);if(value.trim().length<2){setItems([]);return}if(!navigator.geolocation){setMsg('Location is required for nearby suggestions.');return}setBusy(true);navigator.geolocation.getCurrentPosition(async p=>{try{const u=new URL(`${API}/discovery/suggestions`);u.searchParams.set('q',value.trim());u.searchParams.set('latitude',String(p.coords.latitude));u.searchParams.set('longitude',String(p.coords.longitude));u.searchParams.set('limit','10');const token=getToken();const r=await fetch(u,{headers:token?{Authorization:`Bearer ${token}`}:{},cache:'no-store'});if(!r.ok)throw new Error('Nearby search unavailable');setItems(await r.json());setMsg('Results are ranked by text match and nearby distance.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}},()=>{setBusy(false);setMsg('Allow location access to rank nearby stores and live-stock products.')},{enableHighAccuracy:false,timeout:8000});}return <><Nav/><main className="container section"><div className="sectionHead"><div><span className="eyebrow">Nearby discovery</span><h2>Search what you need</h2><p className="muted">One search across nearby stores, products and categories.</p></div></div><div className="panel"><div className="search"><Search size={18}/><input value={q} onChange={e=>search(e.target.value)} placeholder="Milk, rice, pharmacy, Patil Kirana…" aria-label="Nearby search"/></div><p className="muted small"><MapPin size={14}/> {busy?'Checking nearby availability…':msg}</p><div className="stack">{items.map((x,i)=><Link className="card" key={`${x.kind}-${x.store_id}-${i}`} href={x.store_id?`/market/${x.store_id}`:'/market'}><div className="row space"><div><strong>{x.label}</strong><div className="muted small">{x.secondary||x.kind}</div></div><div className="muted small">{x.distance_km!=null?`${x.distance_km.toFixed(1)} km`:''}</div></div></Link>)}</div>{q.length>=2&&!busy&&items.length===0&&<div className="emptyState"><p className="muted">No matching live nearby result. Try a broader term.</p></div>}</div></main></>}
